`timescale 1ns/1ps

module full_adder_using_half_adder_tb;

reg A;
reg B;
reg Cin;

wire Sum;
wire Cout;

full_adder_using_half_adder dut(
    .A(A),
    .B(B),
    .Cin(Cin),
    .Sum(Sum),
    .Cout(Cout)
);

initial begin
    $dumpfile("full_adder_using_half_adder.vcd");
    $dumpvars(0, full_adder_using_half_adder_tb);

    $display("A B Cin | Sum Cout");
    $monitor("%b %b %b | %b %b", A, B, Cin, Sum, Cout);

    A=0; B=0; Cin=0; #10;
    A=0; B=0; Cin=1; #10;
    A=0; B=1; Cin=0; #10;
    A=0; B=1; Cin=1; #10;
    A=1; B=0; Cin=0; #10;
    A=1; B=0; Cin=1; #10;
    A=1; B=1; Cin=0; #10;
    A=1; B=1; Cin=1; #10;

    $finish;
end

endmodule